# dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'

# coleur scheme
# [[plugins]]
# repo = 'tomasr/molokai'
# hook_add = 'colorscheme molokai'

# tree表示
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'map <C-e> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'tpope/vim-fugitive'

# status line
# [[plugins]]
# repo = 'vim-airline/vim-airline'
# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'
# hook_add = """
# let g:airline_powerline_fonts = 1
# let g:airline_theme = 'powerlineish'
# let g:airline#extensions#branch#enabled = 1
# let g:airline_skip_empty_sections = 1
# let g:airline_section_b = '%{airline#extensions#branch#get_head()}'
# """

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'let g:lightline = {"colorscheme": "wombat"}'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#
# [[plugins]]
# repo = 'Shougo/unite.vim'
# hook_add = '''
# '''

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = 'colorscheme onedark'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'
hook_add = '''
  let g:auto_ctags = 1
  let g:auto_ctags_directory_list = ['.git', '.svn']
  nnoremap <C-h> :vsp<CR> :exe("tjump ".expand('<cword>'))<CR>
  nnoremap <C-k> :split<CR> :exe("tjump ".expand('<cword>'))<CR>
'''


[[plugins]]
repo = 'stanangeloff/php.vim'

[[plugins]]
repo = 'othree/html5.vim'
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
[[plugins]]
repo = 'mattn/emmet-vim.git'

[[plugins]]
repo = 'tpope/vim-surround'
